### ISSUE TITLE
Blender 3.5 crash

### ISSUE THREAD

**Issue by Princeamor** [nessaki/Onigiri#4]
get this error when trying to create the reference pose in onigirl. Converting a mixamo animation. Is step 2 in this youtube video used for reference. It works fine in blender 2.8.
https://youtu.be/qs38nki-qYM?si=WAWGMD0uI5HUs4xF
It of course totally causes the operation to not work.

removed 832 unused curves
Traceback (most recent call last):
  File "C:\Users\jeffa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Onigiri\__init__.py", line 18406, i
n execute
    start_frame, end_frame = animutils.get_frame_range(armObj, start=True, end=False)
  File "C:\Users\jeffa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Onigiri\animutils.py", line 3670, i
n get_frame_range
    bpy.context.scene.frame_set(frame_start)
TypeError: Scene.frame_set(): error with argument 1, "frame" -  Function.frame expected an int type, not float
Error: Python: Traceback (most recent call last):
  File "C:\Users\jeffa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Onigiri\__init__.py", line 18406, i
n execute
    start_frame, end_frame = animutils.get_frame_range(armObj, start=True, end=False)
  File "C:\Users\jeffa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Onigiri\animutils.py", line 3670, i
n get_frame_range
    bpy.context.scene.frame_set(frame_start)
TypeError: Scene.frame_set(): error with argument 1, "frame" -  Function.frame expected an int type, not float

**Comment by Gusher** [comment]
Onigiri  is only for Blender 2.80 - 2.81 unless otherwise someone can update it....

**Comment by aiaustin** [comment]
Some functions work fine in Blender 3.x. E.g. the Character Converter functions and use of the Animation Pose Library as I continue to be able to use those to convert Ready Player Me avatars for Second Life and OpenSim right up to Blender 3.6.

**Comment by zaher** [comment]
Hi, I Fixed it in my fork repo, with partial upgrading to Blender 4
https://github.com/zaher/Onigiri
I will not pull request because seem this repo is dead

**Comment by aiaustin** [comment]
Great. I was partially able to use your version zaher on Bledner 4.3 (latest I have installed).  But the export to Collada does not work yet even with your current changes. Is that your experience too?  I think you are right that this original repo is not being updated or maintained but I have a fork (with minor changes) at https://github.com/aiaustin/Onigiri and would be happy to merge in changes there when its full working.

```
rigs::make_complete : warning - bone matching sequence may damage devkits
Traceback (most recent call last):
  File "C:\Users\bat\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Onigiri\__init__.py", line 17420, in execute
    result = rigutils.make_complete(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bat\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Onigiri\rigutils.py", line 3875, in make_complete
    set_bone_groups(armObj)
  File "C:\Users\bat\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Onigiri\rigutils.py", line 3592, in set_bone_groups
    bpy.ops.pose.group_add()
  File "D:\Programs\Blender Foundation\Blender 4.3\4.3\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.pose.group_add" error, could not be found
```

**Comment by zaher** [comment]
Let us move discussing to Discord
Yes any error based on group_add() I can solve it
